stages:
  - build
  - sonarqube
  - docker_build
  - docker_push
build:
  - flutter build web
sonarqube:
  - sonar-scanner -Dsonar.host.url={SONAR_URL} -Dsonar.projectKey={SONAR_PROJECT_KEY} -Dsonar.projectName={SONAR_PROJECT_NAME} -Dsonar.projectVersion={SONAR_PROJECT_VERSION} -Dsonar.sources=lib,pubspec.yaml
docker_build:
  - docker build -t registry.nathanaudvard.fr/imt-framework-front:{TAG} ./
docker_push:
  - docker push registry.nathanaudvard.fr/imt-framework-front:{TAG}