name: imt_framework_front
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  simple_animations: ^5.0.2
  supercharged: ^2.1.1
  build_runner: ^2.1.11
  build_web_compilers: ^3.2.3
  sa4_migration_kit: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/delivery.png

  fonts:
    - family: Sofia
      fonts:
        - asset: assets/fonts/Sofia-Regular.ttf
          weight: 700
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-VariableFont_wght.ttf

  uses-material-design: true




